### PR TITLE
decawave arduino

### PR DESCRIPTION
**Pull request by dewagter**
DWM1000 + Arduino Mini Pro 3.3

### CODE REVIEW

**Comment by kirkscheper** [comment]
.gitignore for the .elf binary?

**Comment by dewagter** [comment]
no, you need this file: it's the precompiled bootloader and fuses.

-Christophe

**Comment by gautierhattenberger** [comment]
which PCB editor did you use ? Altium, Kicad ?

**Comment by gautierhattenberger** [comment]
I also suggest to move the files to misc/decawave/carrier or something like this so we can add decawave anchor PCB without mixing files.

**Comment by dewagter** [comment]
Moved to a subfolder so more decawave boards can be added.

The PCB is Altium, as indicated by the folder name. More info in the README

**Pull request merged**
